title: rpi-aiy-voice-assemble
hero_image: images/banner.png
subtitle: rpi-aiy-voice-assemble subtitle
description: rpi-aiy-voice-assemble description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Step one
    duration: 60
