title: Assemble the AIY Voice Kit
hero_image: images/banner.png
description: How to assemble the AIY Voice Kit
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests:
technology: "raspberry pi, aiy, voice kit"
steps:
  - title: Assemble the kit
